name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  autofix:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install

      - run: pnpm lint

      - uses: autofix-ci/action@v1.3.3