name: 🛡️ CI Main

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - run: corepack enable
      - run: corepack prepare pnpm@latest --activate
      - run: pnpm install --frozen-lockfile

      - run: npx nuxi prepare

      - run: pnpm test